ci_access:
  projects:
    - id: devops-group/Auto-DevOps-NodeJS-Application-Gitlab
user_access:
  access_as:
    agent: {}
  projects:
    - id: devops-group/Auto-DevOps-NodeJS-Application-Gitlab

    